name: 测试

on:
  schedule:
    - cron: '0 0 * * 5'  # 每星期五 UTC 时间 00:00 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: 同步更新软件源
        uses: actions/checkout@v3
        
      - name: Run a script
        run: echo "This is job1"

      - name: Configure Git
        run: |
          git config --global user.name "zjt37"
          git config --global user.email "27096491@qq.com"

      - name: Clone target repository
        run: |
          git clone https://${{ secrets.SOURCE_REPO_TOKEN }}@github.com/zjt37/packages.git
          cd packages
          git checkout main  # 切换到目标仓库的分支

      - name: Copy folder from source to target
        run: |
          git clone https://github.com/fw876/helloworld.git
          mkdir ./packages/helloworld
          cp -r ./helloworld/chinadns-ng ./packages/helloworld/
          cp -r ./helloworld/dns2socks ./packages/helloworld/
          cp -r ./helloworld/dns2tcp ./packages/helloworld/
          cp -r ./helloworld/gn ./packages/helloworld/
          cp -r ./helloworld/hysteria ./packages/helloworld/
          cp -r ./helloworld/ipt2socks ./packages/helloworld/
          cp -r ./helloworld/lua-neturl ./packages/helloworld/
          cp -r ./helloworld/microsocks ./packages/helloworld/
          cp -r ./helloworld/mosdns ./packages/helloworld/
          cp -r ./helloworld/naiveproxy ./packages/helloworld/
          cp -r ./helloworld/redsocks2 ./packages/helloworld/
          cp -r ./helloworld/shadow-tls ./packages/helloworld/
          cp -r ./helloworld/shadowsocks-libev ./packages/helloworld/
          cp -r ./helloworld/shadowsocks-rust ./packages/helloworld/
          cp -r ./helloworld/shadowsocksr-libev ./packages/helloworld/
          cp -r ./helloworld/simple-obfs ./packages/helloworld/
          cp -r ./helloworld/tcping ./packages/helloworld/
          cp -r ./helloworld/trojan ./packages/helloworld/
          cp -r ./helloworld/tuic-client ./packages/helloworld/
          cp -r ./helloworld/v2ray-core ./packages/helloworld/
          cp -r ./helloworld/v2ray-plugin ./packages/helloworld/
          cp -r ./helloworld/v2raya ./packages/helloworld/
          cp -r ./helloworld/xray-core ./packages/helloworld/
          cp -r ./helloworld/xray-plugin ./packages/helloworld/
          
          

      - name: Commit and push changes to target repository
        run: |
          cd packages
          git add .
          git commit --allow-empty -m "Sync folder from source repository (no changes detected)"
          git push origin main
