name: 测试

on:
  schedule:
    - cron: '0 0 * * 5'  # 每星期五 UTC 时间 00:00 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: 同步更新软件源
        uses: actions/checkout@v3
        
      - name: Run a script
        run: echo "This is job1"

      - name: Configure Git
        run: |
          git config --global user.name "zjt37"
          git config --global user.email "27096491@qq.com"

      - name: Clone target repository
        run: |
          git clone https://${{ secrets.SOURCE_REPO_TOKEN }}@github.com/zjt37/packages.git
          cd packages
          git checkout main  # 切换到目标仓库的分支

      - name: Copy folder from source to target
        run: |
          git clone -b js https://github.com/sirpdboy/luci-theme-kucat.git
          ls
          

