name: 上传测试

on:
  schedule:
    - cron: '0 0 * * 5'  # 每星期五 UTC 时间 00:00 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: 同步更新软件源
        uses: actions/checkout@v3
          
      - name: Copy folder from source to target
        run: |
          git clone https://github.com/zjt37/zheng.git
          ls

      - name: Create Release with Timestamp
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SOURCE_REPO_TOKEN }}
        with:
          tag_name: openwrt-${{ env.CURRENT_TIMESTAMP }}  # 动态生成带时间的标签名
          release_name: Release openwrt-${{ env.CURRENT_TIMESTAMP }}
          draft: false
          prerelease: false
          


      - name: Upload firmware
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.SOURCE_REPO_TOKEN }}
          file: zheng/clash.ini
          asset_name: openclash.ini
          tag: openwrt-${{ env.CURRENT_TIMESTAMP }}
          overwrite: true
