name: 编译openwrt固件

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  schedule:
    - cron:  1 0 * * 6
  
  watch:
    types: [started]
    

准备开始:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 清理磁盘空间
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 2048
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: 清理后磁盘空间
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
