name: 同步更新passwall依赖

on:
  schedule:
    - cron: '0 0 * * 5'  # 每星期五 UTC 时间 00:00 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SOURCE_REPO_TOKEN }} # 使用 PAT

- name: Commit and push changes
        run: |
          git config --global user.name "zjt37"
          git config --global user.email "27096491@qq.com"
          git rm ./passwall-package
          git commit -m "删除文件：./passwall-package"
          git push origin main        
