name: Sync

on:
  schedule:
    - cron: '0 0 * * 5'  # 每星期五 UTC 时间 00:00 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

      
    - name: Add SSH key
      run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.TARGET_REPO_SSH_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan github.com >> ~/.ssh/known_hosts

    
    - name: Clone target repository
      run: |
        mkdir -p zheng
        git clone https://github.com/TanZhiwen2001/luci-app-adguardhome.git
        mv luci-app-adguardhome zheng/
        cd zheng
        ls


