name: Sync

on:
  schedule:
    - cron: '0 0 * * 5'  # 每星期五 UTC 时间 00:00 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Clone target repository
      env:
        TARGET_REPO_TOKEN: ${{ secrets.SOURCE_REPO_TOKEN }}
      run: |
        git clone https://$SOURCE_REPO_TOKEN@github.com/zjt37/aaa.git zheng
        cd zheng
        git config --global user.name "zjt37"
        git config --global user.email "27096491@qq.com"
        git clone https://github.com/TanZhiwen2001/luci-app-adguardhome.git

    - name: Copy folder to target repository
      run: |
        cp -r ./luci-app-adguardhome ./zheng
        cd zheng
        git add .
        git commit -m "Automated folder update from source repository"
        git push
