name: Upload Folder to Repository1

on:
  workflow_dispatch:  # 允许手动触发 
     

jobs:
  upload-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload folder
      run: |
        # 创建或清空目标文件夹
        mkdir -p zheng
        rm -rf zheng/*
        git clone https://github.com/TanZhiwen2001/luci-app-adguardhome.git
        

        # 复制要上传的文件夹内容
        cp -r luci-app-adguardhome/luci-app-adguardhome zheng/

        # 配置 Git
        git config --global user.name "zjt37"
        git config --global user.email "27096491@qq.com"

        # 添加、提交并推送更改
        git add zheng
        git commit -m "Automated folder upload"
        git push origin main
